### PR TITLE
:tada: Added Portfolio

### PR DESCRIPTION
**Pull request by varunKT001**
### 🎉 Added my portfolio: [Varun Kumar Tiwari](https://varuntiwari.xyz/)

Any suggestions you might have would be greatly appreciated 😄

image

### CODE REVIEW

**Comment by A1Bullet** [comment]
Hello emma , I'd ry love to join you guys I'm just unable to with the cause
of my father and family stollen all my stuff and rights and my father
threatened on kli g me soon and he brake into my door and slapped me I have
nothing left and my and families life is In total danger I need to leave my
house ASAP so if u can provide and financial support or any kind of sponsor
to settle mythings here within a week or 2 + he came up with a drug dealer
fake reported to local police so if any kind of support can will be really
appreciated I didn't have food for 2weeks now I'm trapped in my house for
more than a year and not allowed to leave country for more than 5 years now
so if any kind of support asap will be returned double after I survive my
life promise

**Comment by paalss** [comment]
Hi! I have some suggestions:
- I would have maintained the `project-card-img img`'s aspect ratio, as it looks a little weird when the image's stretched.
- Also the Projects section looks weird at viewport around 800-820px (the text lines gets really short). Maybe you should increase the `@media`'s max-width, or distribute the image and text columns more evenly

Everything else looks 👍 👏 👌 💯 perfect to me!

**Comment by varunKT001** [comment]
@paalss 

> I would have maintained the project-card-img img's aspect ratio, as it looks a little weird when the image's stretched.

I didn't know about the `aspect-ratio` property at that time 😅 I just looked upon it and I think it's a perfect fit for the current situation.

> Also the Projects section looks weird at viewport around 800-820px (the text lines get really short). Maybe you should increase the @media's max-width, or distribute the image and text columns more evenly

You are right, it looks very weird, I didn't notice that at the time of development. I'll fix that asap 👍 

**Thanks for all your suggestions Paalss** 😄

**Comment by varunKT001** [comment]
@eclectic-coding I have made the changes using the correct alphabetical order.

**Comment by varunKT001** [comment]
@eclectic-coding I have fixed the placement, please check!

**Pull request merged**
