### PR TITLE
Added my portfolio into the readme

### PR DESCRIPTION
**Pull request by Rohithv07**
Added my portfolio site. Please have a look

### CODE REVIEW

**Review by avipatilpro — APPROVED** [review]

**Review by jakeherp — APPROVED** [review]

**Review by jakeherp — CHANGES_REQUESTED** [review]
Please add in alphabetical order.

**Comment by Rohithv07** [comment]
I already added it in the alphabetical order. On 'R' section since I am Rohithv

**Comment by jakeherp** [comment]
> I already added it in the alphabetical order. On 'R' section since I am Rohithv

Last time I checked "o" came before "y" in the alphabet.

**Comment by Rohithv07** [comment]
Please review it as I edited again and made it alphabetic order

**Review by jakeherp — APPROVED** [review]

**Pull request merged**
