### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sadiqabubakar526**
wooza!!!!

> Full Stack Developer

### CODE REVIEW

**Review by NhlanhlaHasane — APPROVED** [review]

**Comment by eclectic-coding** [comment]
Thank you for your interest. Please edit and please in alphabetical order based on your first name.

**Comment by eclectic-coding** [comment]
Thank you for your interest. If you could, please revise this commit so that your site is listed alphabetically by your first name. Thanks again.
Have a nice day.

**Comment by was07** [comment]
Alphabetically, I think it's suppose to be at line 28

```
- [Abhinav Galodha](https://www.galodha.com)
- [Abubakar Suraj dulah](https://tell-dem.netlify.app)  <--
- [Adam Alston](https://www.adamalston.com)
```

**Comment by eclectic-coding** [comment]
Correct.

**Pull request closed without merging**
