### PR TITLE
Add Kunal Gaurav's portfolio

### PR DESCRIPTION
**Pull request by kunalgaurav4**

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
Changes are unclear, can you only change relevant pieces?

**Comment by kunalgaurav4** [comment]
> Changes are unclear, can you only change relevant pieces?

Added my portfolio.

**Comment by anshumanv** [comment]
Can you revert all other formatting changes? Really tough to see what's changed and what not

**Comment by kunalgaurav4** [comment]
> Can you revert all other formatting changes? Really tough to see what's changed and what not

Sorry I am not much aware of git commands.Just added  - [Kunal Gaurav](http://kunalgaurav.me/)

**Review by jakeherp — CHANGES_REQUESTED** [review]
This still has lots of formatting changes in it, please undo before we can merge this.

**Comment by jakeherp** [comment]
Closing this in favour of #293

**Pull request closed without merging**
